name: Docker Image CI

on:
  push:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: login Dockerhub
      run: echo ":Yy277n&&t,H;GN" | docker login -u juanssosa --password-stdin
      
    - name: Build the Docker image
      run: docker build -t apireservesaws .
    - name: Push to Dockerhub
      run: docker push juanssosa/apireservesaws:tagname
